### ISSUE TITLE
系统博客后端

### ISSUE THREAD

**Issue by zhou-ning** [lhlyu/petard#1]
谢谢博主的项目，想问问博主的后端是用什么写的呢

**Comment by lhlyu** [comment]
> 谢谢博主的项目，想问问博主的后端是用什么写的呢

没写后端，用的是mock，写了一个新的，拥抱vue3：[https://github.com/lhlyu/admin-template](https://github.com/lhlyu/admin-template)

**Comment by zhou-ning** [comment]
好，谢谢博主
